# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [devonzugel, T-Mobile, Hmmmm]
patreon: # Replace with a single Patreon username https://www.patreon.com/posts/22854182
open_collective: # Replace with a single Open Collective username. https://drive.google.com/file/d/13uY2LrbDcIGKw2RZDBoo-u_sQRep6T3o/view?usp=drivesdk
ko_fi: # Replace with a single Ko-fi username cesar Pizza vacuum
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username https
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username opensea.io
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['privacychoices@cc.pch.com, 'https://NSA.gov' 'Https://k12/portal' 'https://marloboro.com
Https://justinfamily.family.blog
Https://yahoo.com


"Bing"
